In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [3]:
# Importing Dataset
ds = pd.read_excel("Combine_Cycle_Power_Plant_Dataset.xlsx")
X = ds.iloc[:, :-1].values
y = ds.iloc[:, -1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [6]:
# Splitting dataset into Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [7]:
# In ANN we need to apply feature scalling in the dummy variables as well
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Building ANN

In [8]:
# Initialize ANN
ann = tf.keras.models.Sequential()

In [9]:
# Adding 1st Hidden Layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [10]:
# Adding 2nd Hidden Layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [11]:
# Adding Output Layer
ann.add(tf.keras.layers.Dense(units=1))

# Since we are using ANN for regression, we keep the Activation Function as "None"

Training ANN

In [12]:
# Compiling ANN model
ann.compile(optimizer='adam', loss='mean_squared_error')

# Since we are solving a regression problem, the loss will be "mse" or "mean_squared_error" or "rmse" or "root_mean_squared_error"

In [13]:
# Training ANN model on Training set
ann.fit(X_train, y_train, batch_size = 32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 3ms/step - loss: 202909.8281
Epoch 2/100
240/240 [==============================] - 1s 2ms/step - loss: 180943.3281
Epoch 3/100
240/240 [==============================] - 1s 2ms/step - loss: 130032.0625
Epoch 4/100
240/240 [==============================] - 1s 3ms/step - loss: 76500.6953
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 44468.8516
Epoch 6/100
240/240 [==============================] - 1s 2ms/step - loss: 25689.3164
Epoch 7/100
240/240 [==============================] - 1s 3ms/step - loss: 15301.9697
Epoch 8/100
240/240 [==============================] - 1s 3ms/step - loss: 10375.5889
Epoch 9/100
240/240 [==============================] - 1s 2ms/step - loss: 7420.9253
Epoch 10/100
240/240 [==============================] - 1s 2ms/step - loss: 5162.9517
Epoch 11/100
240/240 [==============================] - 1s 2ms/step - loss: 3559.9360
Epoch 12/100
240/240 [==============================

Predicting the results of Test set

In [14]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2) # Set the number of values after decimal point to 2

# Converting 1 row X len(y_pred) columns to len(y_pred) rows X 1 column
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

# 2nd parameter is the axis we want to concatenate.
# Since we want to concatenate vertically we use 1. For Horizontal concatenation we use 0.

[[432.38 431.23]
 [457.23 460.01]
 [463.14 461.14]
 ...
 [469.52 473.26]
 [442.13 438.  ]
 [458.64 463.28]]
